name: "EnergAI"
description: "EnergAI Addon for HomeAssistant"
version: "1.0.13"
slug: "energai"
init: false
ingress: true
ingress_port: 8000
panel_icon: mdi:weather-lightning
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000