name: "EnergAI"
description: "The AI model that helps you saving electricity!"
version: "1.0.17"
slug: "energai"
init: false
ingress: true
ingress_port: 8000
panel_icon: mdi:weather-lightning
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000