name: "EnergAI"
description: "EnergAI Addon for HomeAssistant"
version: "1.0.1"
slug: "energai"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000